spring:
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: truer
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
