spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tokkit
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  redis:
    host: localhost
    port: 6379

  ## SMTP 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: teamtokkit@gmail.com
    password: ${EMAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  ## jwt 토큰 생성
  jwt:
    secret: ${JWT_SECRET}
    token:
      access-expiration-time: 1800000 # 30분
      refresh-expiration-time: 1209600000 # 14일

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html